language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - pushd examples/gps_basic && pio run && popd
    - pushd examples/lorawan_abp && pio run && popd
    - pushd examples/lorawan_otaa && pio run && popd
    - pushd examples/module_info && pio run && popd
